name: Deploy Backend

on:
    push:
        branches:
            - "TASK/Sachin/LP-13-CI-CD"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH and deploy
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$SSH_PRIVATE_KEY" > ~/keyfile
                  chmod 600 ~/keyfile
                  mkdir -p ~/.ssh
                  ssh -t -i ~/keyfile ubuntu@13.127.204.211 "bash ~/deploy.sh"
